on:
  issues:
    types: [created]
    
jobs:
  label:
    runs-on: ubuntu-latest
    steps:    
      - uses: andymckay/labeler@1.0.2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          add-labels: "needs-triage"
          ignore-if-assigned: true
